### ISSUE TITLE
[Bug] WS2813 not working

### ISSUE THREAD

**Issue by dzervas** [cp2004/OctoPrint-WS281x_LED_Status#124]
**Description of the bug**

I just got a 2 meter (60 leds/m) WS2813 LED strip and it doesn't seem to do anything. I use a Pi 0w (it's not for a 3D printer but for a kind of 2D plotter so even Pi 0 is more than enough) and connected DO to GPIO10 and BO to GND.

**Steps to reproduce**
Tried torch, test red/green/blue/white, nothing.

**What did you expect to happen**

**Logs and screenshots**
`.octoprint/logs/plugin_ws281x_led_status_debug.log`

```
[2021-03-10 18:01:42,590] INFO: Initialising LED strip
[2021-03-10 18:01:42,624] ERROR: Strip failed to initialize, no effects will be run.
[2021-03-10 18:01:42,625] ERROR: Please check your settings.
[2021-03-10 18:01:42,632] ERROR: Here's the exception: ws2811_init failed with code -13 (Unable to initialize SPI)
[2021-03-10 18:01:42,633] INFO: No strip initialised, exiting the effect process.
[2021-03-10 18:10:35,123] INFO: Initialising LED strip
[2021-03-10 18:10:35,154] INFO: Strip successfully initialised
[2021-03-10 18:10:35,176] INFO: Debug logging not enabled, if you are reporting issues please enable it under 'Features' in the settings page.
[2021-03-10 18:10:35,191] INFO: On message recieved, turning on LEDs
[2021-03-10 18:12:47,489] INFO: Kill message recieved, Bye!
[2021-03-10 18:12:47,668] INFO: Initialising LED strip
[2021-03-10 18:12:47,684] INFO: Strip successfully initialised
[2021-03-10 18:12:47,685] INFO: Debug logging not enabled, if you are reporting issues please enable it under 'Features' in the settings page.
[2021-03-10 18:12:47,701] INFO: On message recieved, turning on LEDs
[2021-03-10 18:13:03,184] INFO: Off message recieved, turning off LEDs
[2021-03-10 18:13:05,944] INFO: On message recieved, turning on LEDs
[2021-03-10 18:13:42,731] INFO: Kill message recieved, Bye!
[2021-03-10 18:13:42,914] INFO: Initialising LED strip
[2021-03-10 18:13:42,930] INFO: Strip successfully initialised
[2021-03-10 18:13:42,931] INFO: Debug logging not enabled, if you are reporting issues please enable it under 'Features' in the settings page.
[2021-03-10 18:13:42,936] INFO: On message recieved, turning on LEDs
[2021-03-10 18:13:52,811] INFO: Off message recieved, turning off LEDs
[2021-03-10 18:13:53,765] INFO: On message recieved, turning on LEDs
[2021-03-10 18:13:58,494] INFO: Off message recieved, turning off LEDs
[2021-03-10 18:14:13,499] INFO: On message recieved, turning on LEDs
[2021-03-10 18:14:14,466] INFO: Off message recieved, turning off LEDs
[2021-03-10 18:14:47,541] INFO: Kill message recieved, Bye!
[2021-03-10 18:14:47,724] INFO: Initialising LED strip
[2021-03-10 18:14:47,729] INFO: Strip successfully initialised
[2021-03-10 18:14:47,741] INFO: Debug logging not enabled, if you are reporting issues please enable it under 'Features' in the settings page.
[2021-03-10 18:14:47,747] INFO: Off message recieved, turning off LEDs
[2021-03-10 18:14:57,225] INFO: On message recieved, turning on LEDs
[2021-03-10 18:14:58,329] INFO: Off message recieved, turning off LEDs
[2021-03-10 18:14:58,966] INFO: On message recieved, turning on LEDs
[2021-03-10 18:14:59,445] INFO: Off message recieved, turning off LEDs
[2021-03-10 18:15:01,696] INFO: On message recieved, turning on LEDs
[2021-03-10 18:19:10,490] INFO: Off message recieved, turning off LEDs
[2021-03-10 18:19:11,031] INFO: On message recieved, turning on LEDs
[2021-03-10 18:19:19,643] INFO: Off message recieved, turning off LEDs
[2021-03-10 18:19:20,169] INFO: On message recieved, turning on LEDs
[2021-03-10 18:19:24,023] INFO: Off message recieved, turning off LEDs
[2021-03-10 18:19:24,655] INFO: On message recieved, turning on LEDs
[2021-03-10 18:25:29,614] INFO: Kill message recieved, Bye!
[2021-03-10 18:27:26,862] INFO: Initialising LED strip
[2021-03-10 18:27:26,926] INFO: Strip successfully initialised
[2021-03-10 18:27:26,927] INFO: Debug logging not enabled, if you are reporting issues please enable it under 'Features' in the settings page.
[2021-03-10 18:27:27,029] INFO: On message recieved, turning on LEDs
[2021-03-10 18:31:16,199] INFO: Kill message recieved, Bye!
[2021-03-10 18:31:16,383] INFO: Initialising LED strip
[2021-03-10 18:31:16,399] INFO: Strip successfully initialised
[2021-03-10 18:31:16,401] INFO: Debug logging not enabled, if you are reporting issues please enable it under 'Features' in the settings page.
[2021-03-10 18:31:16,405] INFO: On message recieved, turning on LEDs
[2021-03-10 18:32:40,635] INFO: Kill message recieved, Bye!
[2021-03-10 18:32:40,820] INFO: Initialising LED strip
[2021-03-10 18:32:40,839] INFO: Strip successfully initialised
[2021-03-10 18:32:40,849] DEBUG: Current settings:
 | * STRIP SETTINGS *
 | - led_count: 120
 | - led_pin: 10
 | - led_freq_hz: 800000
 | - led_dma: 10
 | - led_invert: False
 | - led_brightness: 255
 | - led_channel: 0
 | - strip_type: WS2812_STRIP
 | - reverse: False
 | * EFFECT SETTINGS *
 | startup
 | - enabled: True
 | - color: #00ff00
 | - effect: wipe
 | - delay: 75.0
 | idle
 | - enabled: True
 | - color: #00ccf0
 | - effect: wipe2
 | - delay: 75.0
 | disconnected
 | - enabled: True
 | - color: #000000
 | - effect: cycle
 | - delay: 25.0
 | progress_print
 | - enabled: True
 | - color: #00ff00
 | - base: #000000
 | progress_heatup
 | - enabled: True
 | - color: #ff0000
 | - base: #0000ff
 | progress_cooling
 | - enabled: True
 | - color: #ff0000
 | - base: #0000ff
 | failed
 | - enabled: True
 | - color: #ff0000
 | - effect: pulse
 | - delay: 10.0
 | success
 | - enabled: True
 | - color: #000000
 | - effect: rainbow
 | - delay: 25.0
 | paused
 | - enabled: True
 | - color: #0000ff
 | - effect: bounce
 | - delay: 40.0
 | printing
 | - enabled: False
 | - color: #ffffff
 | - effect: solid
 | - delay: 1.0
 | torch
 | - enabled: True
 | - color: #ffffff
 | - effect: solid
 | - delay: 1.0
 | * ACTIVE TIMES *
 | - start: None
 | - end: None
[2021-03-10 18:32:40,862] INFO: On message recieved, turning on LEDs
[2021-03-10 18:32:53,940] DEBUG: Recieved message to change effect: torch
[2021-03-10 18:33:28,481] DEBUG: Recieved message to change effect: startup
```

`.octoprint/logs/octoprint.log`

```
2021-03-10 18:48:41,422 - octoprint.startup - INFO - ******************************************************************************
2021-03-10 18:48:41,438 - octoprint.startup - INFO - Starting OctoPrint 1.5.3
2021-03-10 18:48:41,440 - octoprint.startup - INFO - ******************************************************************************
2021-03-10 18:48:43,961 - octoprint.util.connectivity.connectivity_checker - INFO - Connectivity changed from offline to online
2021-03-10 18:48:44,182 - octoprint.util.connectivity.connectivity_checker - INFO - Connectivity state is currently: online
2021-03-10 18:48:44,184 - octoprint.util.connectivity.connectivity_checker - INFO - Connecting to 8.8.8.8:53 is working
2021-03-10 18:48:44,185 - octoprint.util.connectivity.connectivity_checker - INFO - Resolving octoprint.org is working
2021-03-10 18:48:44,318 - octoprint.startup - INFO - Blacklist processing done, adding 12 blacklisted plugin versions: roomtemp (any), GcodeEditor (0.1.1), GcodeEditor (0.2.0), GcodeEditor (0.2.1), GcodeEditor (0.2.2), GcodeEditor (0.2.3), GcodeEditor (0.2.4), GcodeEditor (0.2.5), GcodeEditor (0.2.6), GcodeEditor (0.2.8), gcodeleveling (0.1.0), gcodeleveling (0.1.1)
2021-03-10 18:48:44,581 - octoprint.plugin.core - INFO - Loading plugins from /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins, /home/pi/.octoprint/plugins and installed plugin packages...
2021-03-10 18:48:48,320 - octoprint.plugin.core - INFO - Plugin GCode Viewer is disabled.
2021-03-10 18:48:48,384 - octoprint.plugin.core - INFO - Plugin Virtual Printer is disabled.
2021-03-10 18:48:51,301 - octoprint.startup - INFO - Added settings overlay from plugin firmware_check
2021-03-10 18:48:51,379 - octoprint.plugin.core - INFO - Found 22 plugin(s) providing 20 mixin implementations, 42 hook handlers
2021-03-10 18:48:52,550 - octoprint.server.heartbeat - INFO - Starting server heartbeat, 900.0s interval
2021-03-10 18:48:52,606 - octoprint.server - INFO - Intermediary server started
2021-03-10 18:48:52,798 - octoprint.filemanager.storage - INFO - Initializing the file metadata for /home/pi/.octoprint/uploads...
2021-03-10 18:48:55,161 - octoprint.filemanager.storage - INFO - ... file metadata for /home/pi/.octoprint/uploads initialized successfully.
2021-03-10 18:48:55,189 - octoprint.server - INFO - Added new permission from plugin action_command_notification: PLUGIN_ACTION_COMMAND_NOTIFICATION_SHOW (needs: "Need(method='role', value='plugin_action_command_notification_show')")
2021-03-10 18:48:55,192 - octoprint.server - INFO - Added new permission from plugin action_command_notification: PLUGIN_ACTION_COMMAND_NOTIFICATION_CLEAR (needs: "Need(method='role', value='plugin_action_command_notification_clear')")
2021-03-10 18:48:55,210 - octoprint.server - INFO - Added new permission from plugin action_command_prompt: PLUGIN_ACTION_COMMAND_PROMPT_INTERACT (needs: "Need(method='role', value='plugin_action_command_prompt_interact')")
2021-03-10 18:48:55,214 - octoprint.server - INFO - Added new permission from plugin announcements: PLUGIN_ANNOUNCEMENTS_READ (needs: "Need(method='role', value='plugin_announcements_read')")
2021-03-10 18:48:55,231 - octoprint.server - INFO - Added new permission from plugin announcements: PLUGIN_ANNOUNCEMENTS_MANAGE (needs: "Need(method='role', value='plugin_announcements_read'), Need(method='role', value='plugin_announcements_manage')")
2021-03-10 18:48:55,235 - octoprint.server - INFO - Added new permission from plugin appkeys: PLUGIN_APPKEYS_ADMIN (needs: "Need(method='role', value='plugin_appkeys_admin')")
2021-03-10 18:48:55,253 - octoprint.server - INFO - Added new permission from plugin backup: PLUGIN_BACKUP_ACCESS (needs: "Need(method='role', value='plugin_backup_access')")
2021-03-10 18:48:55,257 - octoprint.server - INFO - Added new permission from plugin firmware_check: PLUGIN_FIRMWARE_CHECK_DISPLAY (needs: "Need(method='role', value='plugin_firmware_check_display')")
2021-03-10 18:48:55,275 - octoprint.server - INFO - Added new permission from plugin logging: PLUGIN_LOGGING_MANAGE (needs: "Need(method='role', value='plugin_logging_manage')")
2021-03-10 18:48:55,279 - octoprint.server - INFO - Added new permission from plugin pi_support: PLUGIN_PI_SUPPORT_STATUS (needs: "Need(method='role', value='plugin_pi_support_check')")
2021-03-10 18:48:55,297 - octoprint.server - INFO - Added new permission from plugin pluginmanager: PLUGIN_PLUGINMANAGER_MANAGE (needs: "Need(method='role', value='plugin_pluginmanager_manage')")
2021-03-10 18:48:55,300 - octoprint.server - INFO - Added new permission from plugin pluginmanager: PLUGIN_PLUGINMANAGER_INSTALL (needs: "Need(method='role', value='plugin_pluginmanager_manage'), Need(method='role', value='plugin_pluginmanager_install')")
2021-03-10 18:48:55,318 - octoprint.server - INFO - Added new permission from plugin softwareupdate: PLUGIN_SOFTWAREUPDATE_CHECK (needs: "Need(method='role', value='plugin_softwareupdate_check')")
2021-03-10 18:48:55,321 - octoprint.server - INFO - Added new permission from plugin softwareupdate: PLUGIN_SOFTWAREUPDATE_UPDATE (needs: "Need(method='role', value='plugin_softwareupdate_update')")
2021-03-10 18:48:55,324 - octoprint.server - INFO - Added new permission from plugin softwareupdate: PLUGIN_SOFTWAREUPDATE_CONFIGURE (needs: "Need(method='role', value='plugin_softwareupdate_configure')")
2021-03-10 18:49:00,879 - octoprint.util.pip - INFO - Using "/home/pi/oprint/bin/python3 -m pip" as command to invoke pip
2021-03-10 18:49:05,594 - octoprint.util.pip - INFO - Version of pip is 20.3.3
2021-03-10 18:49:05,609 - octoprint.util.pip - INFO - pip installs to /home/pi/oprint/lib/python3.7/site-packages (writable -> yes), --user flag needed -> no, virtual env -> yes
2021-03-10 18:49:05,612 - octoprint.util.pip - INFO - ==> pip ok -> yes
2021-03-10 18:49:06,507 - octoprint.plugins.softwareupdate - INFO - Loaded version cache from disk
2021-03-10 18:49:07,121 - octoprint.plugin.core - INFO - Initialized 20 plugin implementation(s)
2021-03-10 18:49:07,258 - octoprint.plugin.core - INFO - 22 plugin(s) registered with the system:
|  Action Command Notification Support (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/action_command_notification
|  Action Command Prompt Support (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/action_command_prompt
|  Announcement Plugin (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/announcements
|  Anonymous Usage Tracking (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/tracking
|  Application Keys Plugin (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/appkeys
|  Backup & Restore (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/backup
|  Continuous Print (1.2.1) = /home/pi/oprint/lib/python3.7/site-packages/continuousprint
|  Core Wizard (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/corewizard
|  Discovery (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/discovery
|  Error Tracking (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/errortracking
|  File Check (2021.2.23) (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint_file_check
|  Firmware Check (2021.2.4) (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint_firmware_check
| !GCode Viewer (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/gcodeviewer
|  Logging (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/logging
|  OctoKlipper (0.3.2) = /home/pi/oprint/lib/python3.7/site-packages/octoprint_klipper
|  Pi Support Plugin (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/pi_support
|  Plugin Manager (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/pluginmanager
|  Software Update (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/softwareupdate
|  Themeify (1.2.2) = /home/pi/oprint/lib/python3.7/site-packages/octoprint_themeify
|  TouchUI (0.3.17) = /home/pi/oprint/lib/python3.7/site-packages/octoprint_touchui
| !Virtual Printer (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/virtual_printer
|  WS281x LED Status (0.6.0) = /home/pi/oprint/lib/python3.7/site-packages/octoprint_ws281x_led_status
Prefix legend: ! = disabled, # = blacklisted, * = incompatible
2021-03-10 18:49:07,436 - octoprint.environment - INFO - Detected environment is Python 3.7.3 under Linux (linux). Details:
|  hardware:
|      cores: 1
|      freq: 1100.0
|      ram: 386322432
|  os:
|      bits: 32
|      id: linux
|      platform: linux
|  plugins:
|      pi_support:
|          model: Raspberry Pi Zero W Rev 1.1
|          octopi_version: 0.18.0
|          throttle_state: '0x0'
|  python:
|      pip: 20.3.3
|      version: 3.7.3
|      virtualenv: /home/pi/oprint
2021-03-10 18:49:07,534 - octoprint.server - INFO - Reset webasset folder /home/pi/.octoprint/generated/webassets...
2021-03-10 18:49:07,629 - octoprint.server - INFO - Reset webasset folder /home/pi/.octoprint/generated/.webassets-cache...
2021-03-10 18:49:12,986 - octoprint.server - INFO - Shutting down intermediary server...
2021-03-10 18:49:13,257 - octoprint.server - INFO - Intermediary server shut down
2021-03-10 18:49:13,274 - octoprint.events - INFO - Processing startup event, this is our first event
2021-03-10 18:49:13,276 - octoprint.events - INFO - Adding 2 events to queue that were held back before startup event
2021-03-10 18:49:13,319 - octoprint.filemanager - INFO - Adding backlog items from all storage types to analysis queue...
2021-03-10 18:49:13,325 - octoprint.server - INFO - Autoconnect on startup is configured, trying to connect to the printer...
2021-03-10 18:49:13,408 - octoprint.filemanager - INFO - Added 0 items from storage type "local" to analysis queue
2021-03-10 18:49:13,512 - octoprint.plugins.softwareupdate - INFO - Fetching check overlays from https://plugins.octoprint.org/update_check_overlay.json
2021-03-10 18:49:13,522 - octoprint.plugins.pluginmanager - INFO - Loaded plugin repository data from disk, was still valid
2021-03-10 18:49:14,911 - octoprint.server - INFO - Trying to connect to configured serial port /tmp/printer
2021-03-10 18:49:15,091 - octoprint.plugins.tracking - INFO - Sent tracking event system_unthrottled, payload: {'throttled_now': False, 'throttled_past': False, 'throttled_mask': 0, 'throttled_voltage_now': False, 'throttled_voltage_past': False, 'throttled_overheat_now': False, 'throttled_overheat_past': False}
2021-03-10 18:49:16,160 - octoprint.util.comm - INFO - Changing monitoring state from "Offline" to "Opening serial connection"
2021-03-10 18:49:16,218 - octoprint.util.comm - INFO - Connecting to port /tmp/printer, baudrate 250000
2021-03-10 18:49:16,292 - octoprint.server.util.watchdog - INFO - Running initial scan on watched folder...
2021-03-10 18:49:16,326 - octoprint.server.util.watchdog - INFO - ... initial scan done.
2021-03-10 18:49:16,485 - octoprint.util.comm - INFO - Changing monitoring state from "Opening serial connection" to "Error: Connection error, see Terminal tab"
2021-03-10 18:49:16,504 - octoprint.util.comm - INFO - Changing monitoring state from "Error: Connection error, see Terminal tab" to "Offline (Error: Connection error, see Terminal tab)"
2021-03-10 18:49:16,584 - octoprint.plugins.action_command_notification - INFO - Notifications cleared
2021-03-10 18:49:16,607 - octoprint.util.comm - ERROR - Unexpected error while connecting to serial port /tmp/printer, baudrate 250000 from hook default: SerialException: '[Errno 2] could not open port /tmp/printer: [Errno 2] No such file or directory: '/tmp/printer'' @ comm.py:_open_serial:3670
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/serial/serialposix.py", line 322, in open
    self.fd = os.open(self.portstr, os.O_RDWR | os.O_NOCTTY | os.O_NONBLOCK)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/printer'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/util/comm.py", line 3670, in _open_serial
    settings().getFloat(["serial", "timeout", "connection"]),
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/util/comm.py", line 3644, in default
    serial_obj.open()
  File "/home/pi/oprint/lib/python3.7/site-packages/serial/serialposix.py", line 325, in open
    raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
serial.serialutil.SerialException: [Errno 2] could not open port /tmp/printer: [Errno 2] No such file or directory: '/tmp/printer'
2021-03-10 18:49:16,632 - octoprint.plugin - ERROR - Error while calling plugin ws281x_led_status
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/plugin/__init__.py", line 271, in call_plugin
    result = getattr(plugin, method)(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/util/__init__.py", line 1890, in wrapper
    return f(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_ws281x_led_status/__init__.py", line 605, in on_event
    self.update_effect(self.supported_events[event])
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_ws281x_led_status/__init__.py", line 560, in update_effect
    if not self.SETTINGS[mode_name][
KeyError: 'disconnected'
2021-03-10 18:49:17,541 - octoprint.plugins.discovery - INFO - Registered 'OctoPrint instance "HypnoMaster Table"._http._tcp.local.' for _http._tcp.local.
2021-03-10 18:49:17,822 - octoprint.plugins.tracking - INFO - Sent tracking event commerror_connection, payload: {'commerror_text': 'Connection error, see Terminal tab'}
2021-03-10 18:49:18,609 - octoprint.plugins.discovery - INFO - Registered 'OctoPrint instance "HypnoMaster Table"._octoprint._tcp.local.' for _octoprint._tcp.local.
2021-03-10 18:49:18,686 - octoprint.plugins.discovery - INFO - Registered OctoPrint instance "HypnoMaster Table" for SSDP
2021-03-10 18:49:18,960 - octoprint.plugins.ws281x_led_status - INFO - Detected running on a Raspberry Pi Zero
2021-03-10 18:49:18,990 - octoprint.plugins.ws281x_led_status - INFO - Running OS config test (Log Mode)
2021-03-10 18:49:19,182 - octoprint.plugins.ws281x_led_status - INFO - OS config test complete. Results:
| - adduser: passed
| - spi_enabled: passed
| - spi_buffer_increase: passed
| - set_core_freq: passed
| - set_core_freq_min: passed
2021-03-10 18:49:19,485 - octoprint.plugins.ws281x_led_status - INFO - Settings refreshed
2021-03-10 18:49:19,525 - octoprint.server - INFO - Listening on http://127.0.0.1:5000
2021-03-10 18:49:20,135 - octoprint.plugins.pluginmanager - INFO - Loaded plugin repository data from disk, was still valid
2021-03-10 18:49:32,742 - octoprint.util.pip - INFO - Using "/home/pi/oprint/bin/python3 -m pip" as command to invoke pip
2021-03-10 18:49:32,794 - octoprint.util.pip - INFO - pip installs to /home/pi/oprint/lib/python3.7/site-packages (writable -> yes), --user flag needed -> no, virtual env -> yes
2021-03-10 18:49:32,796 - octoprint.util.pip - INFO - ==> pip ok -> yes
2021-03-10 18:49:32,927 - octoprint.plugins.softwareupdate - INFO - Minimum free storage across all update relevant locations is 3.1GB. That is considered sufficient for updating.
2021-03-10 18:49:33,797 - octoprint.plugins.continuousprint - INFO - Continuous Print Plugin started
2021-03-10 18:49:33,843 - octoprint.plugins.themeify - INFO - Themeify initialized.
2021-03-10 18:49:34,072 - octoprint.plugins.ws281x_led_status - INFO - Ws281x LED Status runner started
2021-03-10 18:49:35,161 - octoprint.plugins.tracking - INFO - Sent tracking event ping, payload: {'octoprint_uptime': 44}
2021-03-10 18:49:36,446 - octoprint.plugins.tracking - INFO - Sent tracking event pong, payload: {'version': '1.5.3', 'os': 'linux', 'bits': 32, 'python': '3.7.3', 'pip': '20.3.3', 'cores': 1, 'freq': 1100.0, 'ram': 386322432, 'pi_model': 'Raspberry Pi Zero W Rev 1.1', 'octopi_version': '0.18.0', 'plugins': 'touchui:0.3.17,themeify:1.2.2,ws281x_led_status:0.6.0,klipper:0.3.2,continuousprint:1.2.1'}
2021-03-10 18:49:37,871 - octoprint.plugins.tracking - INFO - Sent tracking event startup, payload: {'version': '1.5.3', 'os': 'linux', 'bits': 32, 'python': '3.7.3', 'pip': '20.3.3', 'cores': 1, 'freq': 1100.0, 'ram': 386322432, 'pi_model': 'Raspberry Pi Zero W Rev 1.1', 'octopi_version': '0.18.0'}
2021-03-10 18:49:39,791 - octoprint.server.preemptive_cache - INFO - Preemptively caching / (ui _default) for {'base_url': 'http://table.lan/', 'path': '/', 'query_string': 'l10n=en'}
2021-03-10 18:49:44,544 - octoprint.server.util.flask - INFO - Passively logging in user admin from ::ffff:10.13.37.111
2021-03-10 18:49:44,569 - octoprint.access.users - INFO - Logged in user: admin
2021-03-10 18:49:53,863 - octoprint.plugins.pluginmanager - INFO - Loaded notice data from disk, was still valid
2021-03-10 18:49:59,037 - octoprint.plugins.pluginmanager - INFO - Loaded notice data from disk, was still valid
```

**Version of plugin and OctoPrint**

OctoPrint (using OctoPi): 1.5.3
plugin: 0.6.0

**Comment by cp2004** [comment]
Hi, WS2813 strips are not supported by this plugin or the underlying library explicitly. You've selected WS2812, presumably because WS2813 is not in the list, the only way it *may* work is if any of the other options (WS2811, SK6182) are compatible.

You can see the list of supported/recommended hardware here: https://cp2004.gitbook.io/ws281x-led-status/guides/setup-guide-1/supported-hardware#led-strips

**Comment by dzervas** [comment]
Oh forgot to mention that the underlying library seems to work with WS2813: https://github.com/jgarff/rpi_ws281x/issues/152

**Comment by dzervas** [comment]
I connected to the wrong side of the strip -.-
I now have flickering leds but that's probably due to doing nothing about the voltage difference (I'm currently testing so I haven't hooked either a diode or a level shifter)

**Comment by dzervas** [comment]
you're right! I tested by quickly soldering 2 jumper cables on the other side of the 2m strip and that was causing the flicker (I found that out just after I made a circuit with a transistor for the level shifting).
When I properly soldered the 4 cables on the right side (where BI and DI are), the whole strip worked without any level shifting.

out of topic but do you know a plugin where I can just change the led strip effects? the whole setup is for a sand table, so there's no actual printing taking place, thus most features of this plugin do not apply to me, only the torch

awesome plugin, I'll definitely add a strip to my prusa and use this plugin like it's meant to!
