### ISSUE TITLE
[Bug]: Issue with Python 3.12 in versioneer.py

### ISSUE THREAD

**Issue by abacon118** [cp2004/OctoPrint-WS281x_LED_Status#224]
### Description of the bug

When I attempt to install this plugin on OctoPrint 1.10.1 on an Orange Pi 3B, I get the error below.  It appearrs that a couple of commands in versioneer.py are no longer supported in Python 3.12.

### Steps to reproduce

Install the plugin

### What happened instead?

Installing plugin "WS281x LED Status" from https://github.com/cp2004/OctoPrint-WS281x_LED_Status/releases/latest/download/release.zip...
/home/ubuntu/OctoPrint/venv/bin/python3 -m pip --disable-pip-version-check install file:///tmp/tmp4js4t277/release.zip --no-cache-dir
Processing /tmp/tmp4js4t277/release.zip
Preparing metadata (setup.py): started
Preparing metadata (setup.py): finished with status 'error'
error: subprocess-exited-with-error

× python setup.py egg_info did not run successfully.
│ exit code: 1
╰─> [18 lines of output]
/tmp/pip-req-build-eo08smi3/versioneer.py:526: SyntaxWarning: invalid escape sequence '\s'
] = '''# -*- coding: utf-8 -*-
Traceback (most recent call last):
File "<string>", line 2, in <module>
File "<pip-setuptools-caller>", line 34, in <module>
File "/tmp/pip-req-build-eo08smi3/setup.py", line 16, in <module>
plugin_version = versioneer.get_version()
^^^^^^^^^^^^^^^^^^^^^^^^
File "/tmp/pip-req-build-eo08smi3/versioneer.py", line 1955, in get_version
return get_versions()["version"]
^^^^^^^^^^^^^^
File "/tmp/pip-req-build-eo08smi3/versioneer.py", line 1866, in get_versions
cfg = get_config_from_root(root)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/tmp/pip-req-build-eo08smi3/versioneer.py", line 443, in get_config_from_root
parser = configparser.SafeConfigParser()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
[end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
Error!
Could not parse output from pip, see plugin_pluginmanager_console.log for generated output

### Plugin version

0.8

### OctoPrint version

1.10.1

**Comment by cp2004** [comment]
I'm aware of this issue, however you still won't be able to use this plugin on your Orange Pi. The library using the GPIO hardware only supports Raspberry Pis.

I need to make changes across all of my plugins, which probably means that I won't merge the PR submitted here, as I'm looking to replace versioneer with a modernised version, or completely in this plugin and all others.
